In [27]:
from Crypto.Hash import MD5
hash = MD5.new()
message=b"Hello Vedika"
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
4fb6563dd4ad9e2bc16f28491b12729b


In [31]:
from Crypto.Hash import MD5
hash = MD5.new()
hash.update(b'Hello ')
hash.update(b'Vedika')
print(hash.hexdigest())

4fb6563dd4ad9e2bc16f28491b12729b


In [40]:
def HEval(list_g,list_message):
    h=1
    for i in range(len(list_g)):
        print(list_g[i], list_message[i])
        h=h*(list_g[i]**(int(list_message[i],2)+1))
    return h


In [41]:
g=[2,3]
m=[b'101',b'111']
HEval(g,m)

419904

In [7]:
import Crypto.Util.number
import Crypto
import sys
import random
p=Crypto.Util.number.getPrime(5, randfunc=None) #Crypto.Random.get_random_bytes
print ("\nRandom n-bit Prime (p): ",p)


Random n-bit Prime (p):  29


In [75]:
import
random.sarandom.sa

[20, 13, 93, 19, 75, 77, 38]

In [41]:
import Crypto.Util.number
import Crypto
import random
import sys

n=5

def getPrime(k):
    #should return k+1 bit prime
    p=Crypto.Util.number.getPrime(k+1, randfunc=None) #randfunc=Crypto.Random.get_random_bytes
    return p

def SelectG(p,n):
    #should select randomly g1,..,gn from 0,..,p and return that
    g=random.sample(range(2,p),n)
    return g

def HGen(k):
    #should return hash family p,g1,..,gn
    p=getPrime(k)
    g=SelectG(p,n)
    print(p," ",g," ")
    return p,g

def HEval(p,list_g,list_message):
    h=1
    for i in range(len(list_g)):
        h=h*(list_g[i]**(int(list_message[i],2)+1))
    return h

def IncH(p,g,M,h,j,m):
    print(M[j])
    print(int(M[j],2))
    x=int(h/(g[j]**(int(M[j],2)+1)))
    y=x*(g[j]**(int(m,2)+1))
    return y

def main():
    M=[b'101',b'101',b'101',b'101',b'101']
    p,g = HGen(20)
    h=HEval(p,g,M)
    h1=IncH(p,g,M,h,2,b'111')
    M1=[b'101',b'101',b'111',b'101',b'101']
    h2=HEval(p,g,M1)
    print(h," ")
    print(h1)
    print(h2)


In [42]:
import time
start = time.process_time()
main()    
print(time.process_time() - start)

2063483   [1126102, 379344, 1565237, 1650518, 83157]  
b'101'
5
597393917380790466841018476725060416042638280714589749141359769853232198598842218764803131729591948552854508432428713875022943909651497476864060887249146120829860181186707456  
1463595303633837710415072772085709272659545010378411301503583181917415949965421757098237420228358934633057397294059238096124294280735518845152674978334741760926075335239788705164243763200
1463595303633837720686520546566322333719173841285157557620349053930694370676691303498895454721785274917171234683600360825881130213301543946330653833556996172770695561740436197455706456064
0.00992202200000003


In [6]:
fo = open("test1.jpeg","rb")
image = fo.read()
fo.close()
image = bytearray(image)
key = 48
for index, value in enumerate(image):
    image[index]=value^key
fo = open("enc.jpeg","wb")
fo.write(image)
fo.close()

In [9]:
fo = open("enc.jpeg","rb")
image = fo.read()
fo.close()
image = bytearray(image)
key = 48
for index, value in enumerate(image):
    image[index]=value^key
fo = open("denc.jpeg","wb")
fo.write(image)
fo.close()

FileNotFoundError: [Errno 2] No such file or directory: 'enc.jpeg'

In [20]:
import sys

In [51]:
fo = open("pic1.png","rb")
image1 = fo.read()
print(type(image1))
fo.close()
image1 = bytearray(image1)
print(image1[500])
#print(sys.getsizeof(image1[256]))
#print(len(image1))
fo = open("pic1-up.png","wb")
fo.write(image1)
fo.close()

<class 'bytes'>
59


In [45]:
fo2 = open("pic2.png","rb")
image2 = fo2.read()
fo2.close()
image2 = bytearray(image2)
print(image2[500])
print(sys.getsizeof(image2[256]))
print(len(image2))

59
28
114997


In [58]:
from PIL import Image

im = Image.new(mode = "RGB", size = (200, 200), color = (153, 153, 255) )
pixels = im.load()
pixels[10,10] = (0,0,0)
im.show()

In [95]:
from PIL import Image

# PIL accesses images in Cartesian co-ordinates, so it is Image[columns, rows]
img = Image.new( 'RGB', (20,20), "green") # create a new black image
pixels = img.load() # create the pixel map
print(pixels)
img.show()
img.save('pic1.jpg')
for i in range(img.size[0]):    # for every col:
        pixels[i,i] = (255, 255, 255) # set the colour accordingly
        #pixels[i,19-i] = (255, 255, 255)
img.show()
img.save('pic2.jpg')

In [97]:
fo1 = open("pic1.jpg","rb")
im1 = fo1.read()
fo1.close()
im1 = bytearray(im1)
#print(len(im1))
fo2 = open("pic2.jpg","rb")
im2 = fo2.read()
fo2.close()
im2 = bytearray(im2)
#print(len(im2))
#print(im2)
#im1

In [98]:
from PIL import Image, ImageChops

pixelsDifference = ImageChops.difference(Image.open('pic1.jpg'), Image.open('pic2.jpg')).convert('L')
pixelsDifference = pixelsDifference.point(([0] + ([255] * 255)))
Img = pixelsDifference.convert('RGB')
print(Img)

<PIL.Image.Image image mode=RGB size=20x20 at 0x7F2AFDF149E8>


In [100]:
import matplotlib.pyplot as plt 
import matplotlib.image as img 
  
# reading the image 
testImage = img.imread('pic1.jpg') 
  
# displaying the image as an array 
print(len(testImage))
#print(testImage)

# reading the image 
testImage2 = img.imread('pic2.jpg') 
  
# displaying the image as an array 
print(len(testImage2))
#print(testImage2)


20
20


In [5]:
import numpy as np
from PIL import Image

a=np.array(Image.open('pic1.jpg').convert('L'))
print(a)
a[0][0] = 255
print(a)
b=np.array(Image.open('pic2.jpg').convert('L'))
print(b)
img = Image.fromarray(b, 'RGB')
img.save('test.jpg')
img.show()

[[75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75

ValueError: not enough image data

In [114]:
import numpy as np
a=np.array(Image.open('pic1.jpg').convert('L'))
key = 48

b=enumerate(a)
print(b)

In [9]:
import skimage.io

# read image
image = skimage.io.imread(fname="pic1.jpg")

In [8]:
import base64
 
with open("pic1.jpg", "rb") as imageFile:
    str = base64.b64encode(imageFile.read())
    print(str)
    print(len(str))
with open("pic2.jpg", "rb") as imageFile:
    str = base64.b64encode(imageFile.read())
    print(str)
    print(len(str))


b'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAUABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDiqKKK+aPjwooooAKKKKACiiigD//Z'
860
b'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQ

In [10]:
import skimage.io
from Crypto.Hash import MD5
import hashlib 
  

# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
#print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#Now B has 80 blocks with 15 bytes size each
#We encode blocks in counter mode using IV = 19891, cnt = 49 starting
list_blocks_int = []
blocks_cipher_list = []
counter = 49
IV = 19891
final_hash = 0
for i in range(len(B)):
    x= (int(B[i], base=2))
    c= x^counter^IV
    counter+=1
    final_hash^=c
    list_blocks_int.append(x)
    blocks_cipher_list.append(c)
print(final_hash)
print(type(final_hash))
hash = MD5.new()
message=bin(final_hash)
hash.update(message)
print(hash.hexdigest())

decrypted_blocks_list=[]

counter=49
for i in range(len(B)):
    x= blocks_cipher_list[0]
    c= x^counter^IV
    counter+=1
    decrypted_blocks_list.append(c)
print(decrypted_blocks_list)


[[[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 ...

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]]


In [51]:

import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#Now B has 80 blocks with 15 bytes size each
#We encode blocks in counter mode using IV = 19891, cnt = 49 starting
list_blocks_int = []
blocks_cipher_list = []
counter = 49
IV = 19891
final_hash_int = 0
for i in range(len(B)):
    x= (int(B[i], base=2))
    #print(x)
    c= x^counter^IV
    counter+=1
    final_hash_int^=c
    list_blocks_int.append(x)
    blocks_cipher_list.append(str(c))
print(final_hash_int)
temp=[]
for i in range(len(blocks_cipher_list)):
    temp.append(bin(int(blocks_cipher_list[i]))[2:].zfill(8))

final_hash_str = ''.join(temp)
print((final_hash_str))
hash = MD5.new()
message=str(final_hash_int).encode('utf-8')
#print(message)
hash.update(message)
print(hash.hexdigest())
final_hash = hash.hexdigest()

decrypted_blocks_list=[]

counter=49
#for i in range(len(B)):
#    x= blocks_cipher_list[i]
#    c= x^counter^IV
#    counter+=1
#    decrypted_blocks_list.append(c)
#print(decrypted_blocks_list)



1200
176
1100110110000011110011011000000011001101100000011100110110000110110011011000011111001101100001001100110110000101110011011000101011001101100010111100110110001000110011011000100111001101100011101100110110001111110011011000110011001101100011011100110111110010110011011111001111001101111100001100110111110001110011011111011011001101111101111100110111110100110011011111010111001101111110101100110111111011110011011111100011001101111110011100110111111110110011011111111111001101111111001100110111111101110011011110001011001101111000111100110111100000110011011110000111001101111001101100110111100111110011011110010011001101111001011100110111101010110011011110101111001101111010001100110111101001110011011110111011001101111011111100110111101100110011011110110111001101110100101100110111010011110011011101000011001101110100011100110111010110110011011101011111001101110101001100110111010101110011011101101011001101110110111100110111011000110011011101100111001101110111101100110111011111110011011101110

In [21]:
import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
print(b)
print(len(b))
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#print(len(B))

1200
['00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000'

In [17]:
## CODE FOR ARRAY TO IMAGE

from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
print(data)
data[0:256, 0:256] = [255, 0, 0] # red patch in upper left
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [30]:
import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
#print(b)
D=[]
t=''
for i in range(len(b)):
    if(i%8==0):
        t = b[i]
    
    else:
        t+=b[i]
        if((i+1)%8==0):
            D.append(t)
        elif(i==len(b)-1):
            D.append(t)
# D CONSISTS OF 150 BLOCKS OF MESSAGES, LENGTH 64 BITS EACH

1200


In [33]:
from Crypto.Hash import MD5
R =[]
#for i in D:
hash = MD5.new()
message=D[0].encode('utf-8')
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
a25a3530e4b08bf36e4eba4a62d55ce9


In [39]:
import hashlib

a = hashlib.md5(D[0].encode('utf-8'))
b = a.hexdigest()
as_int = int(b, 16)
print(as_int)
print(len(bin(as_int)[2:]))


215803320875861314203172436546581519593
128


In [55]:
def randomizer(D_is_array_64bits_blocks):
    R=[]
    for i in D_is_array_64bits_blocks:
        a = hashlib.md5(i.encode('utf-8'))
        b = a.hexdigest()
        as_int = int(b, 16)
        
        as_bin = bin(as_int)[2:66]   # taking a 64bit no. to randomize
        randomizer_number = int(as_bin, 2)
        print(as_int,as_bin,randomizer_number)
        R.append(bin(randomizer_number*int(i,2)%9223372036854775808)[2:].zfill(64))   # 2 to the power 63
    return R
print(int('0011101110111000000110111101110101100100110111011101110111000010',2))
R= randomizer(['0011101110111000000110111101110101100100110111011101110111000010'])
print(R[0])

4303220081646493122
83956083415494437196646467121856018425 1111110010100101011010011111110110010000101101110001101100010100 18205073606490659604
0001111010010101001010001111111111101101011001101100100100101000


In [56]:
18205073606490659604*4303220081646493122%9223372036854775808

2203712672332433704

In [57]:
bin(2203712672332433704)

'0b1111010010101001010001111111111101101011001101100100100101000'

In [58]:
print('1111010010101001010001111111111101101011001101100100100101000'=='1111010010101001010001111111111101101011001101100100100101000')

True


In [ ]:
# Hexadecimal to binary conversion 
def hex2bin(s): 
    mp = {'0' : "0000",  '1' : "0001", '2' : "0010", '3' : "0011", '4' : "0100", 
          '5' : "0101",  '6' : "0110", '7' : "0111",  '8' : "1000", '9' : "1001",  
          'A' : "1010", 'B' : "1011",  'C' : "1100", 'D' : "1101",  'E' : "1110", 
          'F' : "1111" } 
    bin = "" 
    for i in range(len(s)): 
        bin = bin + mp[s[i]] 
    return bin
      
# Binary to hexadecimal conversion 
def bin2hex(s): 
    mp = {"0000" : '0',  "0001" : '1', "0010" : '2',  "0011" : '3', "0100" : '4', 
          "0101" : '5',  "0110" : '6', "0111" : '7',  "1000" : '8', "1001" : '9',  
          "1010" : 'A', "1011" : 'B',  "1100" : 'C', "1101" : 'D',  "1110" : 'E', 
          "1111" : 'F' } 
    hex = "" 
    for i in range(0,len(s),4): 
        ch = "" 
        ch = ch + s[i] 
        ch = ch + s[i + 1]  
        ch = ch + s[i + 2]  
        ch = ch + s[i + 3]  
        hex = hex + mp[ch]           
    return hex

# Binary to decimal conversion 
def bin2dec(binary):  
        
    binary1 = binary  
    decimal, i, n = 0, 0, 0
    while(binary != 0):  
        dec = binary % 10
        decimal = decimal + dec * pow(2, i)  
        binary = binary//10
        i += 1
    return decimal 
  
# Decimal to binary conversion 
def dec2bin(num):  
    res = bin(num).replace("0b", "") 
    if(len(res)%4 != 0): 
        div = len(res) / 4
        div = int(div) 
        counter =(4 * (div + 1)) - len(res)  
        for i in range(0, counter): 
            res = '0' + res 
    return res 

# Permute function to rearrange the bits 
def permute(k, arr, n): 
    permutation = "" 
    for i in range(0, n): 
        permutation = permutation + k[arr[i] - 1] 
    return permutation 
  
# shifting the bits towards left by nth shifts 
def shift_left(k, nth_shifts): 
    s = "" 
    for i in range(nth_shifts): 
        for j in range(1,len(k)): 
            s = s + k[j] 
        s = s + k[0] 
        k = s 
        s = ""  
    return k     
  
# calculating xow of two strings of binary number a and b 
def xor(a, b): 
    ans = "" 
    for i in range(len(a)): 
        if a[i] == b[i]: 
            ans = ans + "0"
        else: 
            ans = ans + "1"
    return ans 

# Table of Position of 64 bits at initail level: Initial Permutation Table 
initial_perm = [58, 50, 42, 34, 26, 18, 10, 2,  
                60, 52, 44, 36, 28, 20, 12, 4,  
                62, 54, 46, 38, 30, 22, 14, 6,  
                64, 56, 48, 40, 32, 24, 16, 8,  
                57, 49, 41, 33, 25, 17, 9, 1,  
                59, 51, 43, 35, 27, 19, 11, 3,  
                61, 53, 45, 37, 29, 21, 13, 5,  
                63, 55, 47, 39, 31, 23, 15, 7]  
  
# Expansion D-box Table 
exp_d = [32, 1 , 2 , 3 , 4 , 5 , 4 , 5,  
         6 , 7 , 8 , 9 , 8 , 9 , 10, 11,  
         12, 13, 12, 13, 14, 15, 16, 17,  
         16, 17, 18, 19, 20, 21, 20, 21,  
         22, 23, 24, 25, 24, 25, 26, 27,  
         28, 29, 28, 29, 30, 31, 32, 1 ] 
  
# Straight Permutaion Table 
per = [ 16,  7, 20, 21, 
        29, 12, 28, 17,  
         1, 15, 23, 26,  
         5, 18, 31, 10,  
         2,  8, 24, 14,  
        32, 27,  3,  9,  
        19, 13, 30,  6,  
        22, 11,  4, 25 ] 

# S-box Table 
sbox =  [[[14, 4, 13, 1, 2, 15, 11, 8, 3, 10, 6, 12, 5, 9, 0, 7],  
          [ 0, 15, 7, 4, 14, 2, 13, 1, 10, 6, 12, 11, 9, 5, 3, 8],  
          [ 4, 1, 14, 8, 13, 6, 2, 11, 15, 12, 9, 7, 3, 10, 5, 0],  
          [15, 12, 8, 2, 4, 9, 1, 7, 5, 11, 3, 14, 10, 0, 6, 13 ]], 
             
         [[15, 1, 8, 14, 6, 11, 3, 4, 9, 7, 2, 13, 12, 0, 5, 10],  
            [3, 13, 4, 7, 15, 2, 8, 14, 12, 0, 1, 10, 6, 9, 11, 5],  
            [0, 14, 7, 11, 10, 4, 13, 1, 5, 8, 12, 6, 9, 3, 2, 15],  
           [13, 8, 10, 1, 3, 15, 4, 2, 11, 6, 7, 12, 0, 5, 14, 9 ]],  
    
         [ [10, 0, 9, 14, 6, 3, 15, 5, 1, 13, 12, 7, 11, 4, 2, 8],  
           [13, 7, 0, 9, 3, 4, 6, 10, 2, 8, 5, 14, 12, 11, 15, 1],  
           [13, 6, 4, 9, 8, 15, 3, 0, 11, 1, 2, 12, 5, 10, 14, 7],  
            [1, 10, 13, 0, 6, 9, 8, 7, 4, 15, 14, 3, 11, 5, 2, 12 ]],  
        
          [ [7, 13, 14, 3, 0, 6, 9, 10, 1, 2, 8, 5, 11, 12, 4, 15],  
           [13, 8, 11, 5, 6, 15, 0, 3, 4, 7, 2, 12, 1, 10, 14, 9],  
           [10, 6, 9, 0, 12, 11, 7, 13, 15, 1, 3, 14, 5, 2, 8, 4],  
            [3, 15, 0, 6, 10, 1, 13, 8, 9, 4, 5, 11, 12, 7, 2, 14] ],  
         
          [ [2, 12, 4, 1, 7, 10, 11, 6, 8, 5, 3, 15, 13, 0, 14, 9],  
           [14, 11, 2, 12, 4, 7, 13, 1, 5, 0, 15, 10, 3, 9, 8, 6],  
            [4, 2, 1, 11, 10, 13, 7, 8, 15, 9, 12, 5, 6, 3, 0, 14],  
           [11, 8, 12, 7, 1, 14, 2, 13, 6, 15, 0, 9, 10, 4, 5, 3 ]],  
        
         [ [12, 1, 10, 15, 9, 2, 6, 8, 0, 13, 3, 4, 14, 7, 5, 11],  
           [10, 15, 4, 2, 7, 12, 9, 5, 6, 1, 13, 14, 0, 11, 3, 8],  
            [9, 14, 15, 5, 2, 8, 12, 3, 7, 0, 4, 10, 1, 13, 11, 6],  
            [4, 3, 2, 12, 9, 5, 15, 10, 11, 14, 1, 7, 6, 0, 8, 13] ],  
          
          [ [4, 11, 2, 14, 15, 0, 8, 13, 3, 12, 9, 7, 5, 10, 6, 1],  
           [13, 0, 11, 7, 4, 9, 1, 10, 14, 3, 5, 12, 2, 15, 8, 6],  
            [1, 4, 11, 13, 12, 3, 7, 14, 10, 15, 6, 8, 0, 5, 9, 2],  
            [6, 11, 13, 8, 1, 4, 10, 7, 9, 5, 0, 15, 14, 2, 3, 12] ],  
         
         [ [13, 2, 8, 4, 6, 15, 11, 1, 10, 9, 3, 14, 5, 0, 12, 7],  
            [1, 15, 13, 8, 10, 3, 7, 4, 12, 5, 6, 11, 0, 14, 9, 2],  
            [7, 11, 4, 1, 9, 12, 14, 2, 0, 6, 10, 13, 15, 3, 5, 8],  
            [2, 1, 14, 7, 4, 10, 8, 13, 15, 12, 9, 0, 3, 5, 6, 11] ] ] 
    
# Final Permutaion Table 
final_perm = [ 40, 8, 48, 16, 56, 24, 64, 32,  
               39, 7, 47, 15, 55, 23, 63, 31,  
               38, 6, 46, 14, 54, 22, 62, 30,  
               37, 5, 45, 13, 53, 21, 61, 29,  
               36, 4, 44, 12, 52, 20, 60, 28,  
               35, 3, 43, 11, 51, 19, 59, 27,  
               34, 2, 42, 10, 50, 18, 58, 26,  
               33, 1, 41, 9, 49, 17, 57, 25 ] 

def encrypt(pt, rkb, rk): 
    pt = hex2bin(pt) 
      
    # Initial Permutation 
    pt = permute(pt, initial_perm, 64) 
    print("After inital permutation", bin2hex(pt)) 
      
    # Splitting 
    left = pt[0:32] 
    right = pt[32:64] 
    for i in range(0, 16): 
        #  Expansion D-box: Expanding the 32 bits data into 48 bits  
        right_expanded = permute(right, exp_d, 48) 
          
        # XOR RoundKey[i] and right_expanded  
        xor_x = xor(right_expanded, rkb[i]) 
  
        # S-boxex: substituting the value from s-box table by calculating row and column  
        sbox_str = "" 
        for j in range(0, 8): 
            row = bin2dec(int(xor_x[j * 6] + xor_x[j * 6 + 5])) 
            col = bin2dec(int(xor_x[j * 6 + 1] + xor_x[j * 6 + 2] + xor_x[j * 6 + 3] + xor_x[j * 6 + 4])) 
            val = sbox[j][row][col] 
            sbox_str = sbox_str + dec2bin(val) 
              
        # Straight D-box: After substituting rearranging the bits   
        sbox_str = permute(sbox_str, per, 32) 
          
        # XOR left and sbox_str 
        result = xor(left, sbox_str) 
        left = result 
          
        # Swapper 
        if(i != 15): 
            left, right = right, left  
        print("Round ", i + 1, " ", bin2hex(left), " ", bin2hex(right), " ", rk[i]) 
      
    # Combination 
    combine = left + right 
      
    # Final permutaion: final rearranging of bits to get cipher text 
    cipher_text = permute(combine, final_perm, 64) 
    return cipher_text 

pt = "123456ABCD132536"
key = "AABB09182736CCDD"
  
# Key generation 
# --hex to binary 
key = hex2bin(key) 
  
# --parity bit drop table 
keyp = [57, 49, 41, 33, 25, 17, 9,  
        1, 58, 50, 42, 34, 26, 18,  
        10, 2, 59, 51, 43, 35, 27,  
        19, 11, 3, 60, 52, 44, 36,  
        63, 55, 47, 39, 31, 23, 15,  
        7, 62, 54, 46, 38, 30, 22,  
        14, 6, 61, 53, 45, 37, 29,  
        21, 13, 5, 28, 20, 12, 4 ] 
  
# getting 56 bit key from 64 bit using the parity bits  
key = permute(key, keyp, 56) 
  
# Number of bit shifts  
shift_table = [1, 1, 2, 2,  
                2, 2, 2, 2,  
                1, 2, 2, 2,  
                2, 2, 2, 1 ] 
  
# Key- Compression Table : Compression of key from 56 bits to 48 bits 
key_comp = [14, 17, 11, 24, 1, 5,  
            3, 28, 15, 6, 21, 10,  
            23, 19, 12, 4, 26, 8,  
            16, 7, 27, 20, 13, 2,  
            41, 52, 31, 37, 47, 55,  
            30, 40, 51, 45, 33, 48,  
            44, 49, 39, 56, 34, 53,  
            46, 42, 50, 36, 29, 32 ] 

# Splitting  
left = key[0:28]    # rkb for RoundKeys in binary  
right = key[28:56]  # rk for RoundKeys in hexadecimal  
  
rkb = [] 
rk  = [] 
for i in range(0, 16): 
    # Shifting the bits by nth shifts by checking from shift table 
    left = shift_left(left, shift_table[i]) 
    right = shift_left(right, shift_table[i]) 
      
    # Combination of left and right string 
    combine_str = left + right 
      
    # Compression of key from 56 to 48 bits  
    round_key = permute(combine_str, key_comp, 48) 
   
    rkb.append(round_key) 
    rk.append(bin2hex(round_key)) 
  
print("Encryption") 
cipher_text = bin2hex(encrypt(pt, rkb, rk)) 
print("Cipher Text : ",cipher_text) 
  
print("Decryption") 
rkb_rev = rkb[::-1] 
rk_rev = rk[::-1] 
text = bin2hex(encrypt(cipher_text, rkb_rev, rk_rev)) 
print("Plain Text : ",text) 