In [27]:
from Crypto.Hash import MD5
hash = MD5.new()
message=b"Hello Vedika"
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
4fb6563dd4ad9e2bc16f28491b12729b


In [11]:
from PIL import Image
import numpy as np


pic1_arr = Image.open("pic1.jpg")
pic2_arr = Image.open("pic2.jpg")

pic1_arr = np.array(pic1_arr.getdata())
pic2_arr = np.array(pic2_arr.getdata())

update_indices =[]

for i in range(400):
    if(pic1_arr[i]!=pic2_arr[i]):
        update_indices.append(i)
        


[[  0 128   1]
 [  0 128   1]
 [  0 128   1]
 ...
 [  0 128   1]
 [  0 128   1]
 [  0 128   1]] [[255 255 204]
 [ 33 112  29]
 [  0 139  21]
 ...
 [ 28 125  28]
 [ 28 118  30]
 [178 255 181]]


In [4]:
if((1==0)&1):
    print("hi")

In [8]:
from PIL import Image
import numpy as np

w, h = 256,256
data = np.zeros((h, w, 3), dtype=np.uint8)
data[:, :] = [255, 0, 0] # red patch in upper left
img = Image.fromarray(data, 'RGB')
img.save('pic1.png')
data[150,150] = [255,255,255]
data[0,0] =[255,255,255]
img = Image.fromarray(data, 'RGB')
img.save('pic2.png')

img.show()

In [1]:
[0]*5

[0, 0, 0, 0, 0]

In [11]:
R =[1,2,3,4]
h=0
for i in range(len(R)):
    h=h^R[i]
print(h)
h^=4
print(h)

4
0


In [1]:
import image_processing as ip
import encryption_module as em

def incremental_update_genrate_hash(key_tag,tag,indices_to_update_list_sorted,original_message_list,updated_messages_list_ac_indices):
    ### TAG IS OF STR TYPE
    ### 2nd argument should be str type
    h = DES.decrypt_DES(key_tag,tag)
    print("From em module line 56 h we have decrypted",h)
    h=int(h,16)

    R = randomize_blocks(original_message_list)
    R_new = randomize_blocks(updated_messages_list_ac_indices)

    ### str type
    N = len(R)
    #visited =[0]*N
    nb = len(indices_to_update_list_sorted)

    for i in range(nb):
        j = indices_to_update_list_sorted[i]
        if(j!=0 & j!=N-1):
            h=h^f1( hex(int(R[j],2))[2:] , R[j+1])^f1( hex(int(R[j-1],2))[2:] , R[j])
            R[j]=R_new[i]
            h=h^f1( hex(int(R[j],2))[2:] , R[j+1])^f1( hex(int(R[j-1],2))[2:] , R[j])
        if(j==0):
                h=h^f1( hex(int(R[0],2))[2:] , R[1])^f1( hex(int(R[N-1],2))[2:] , R[0])
                R[j]=R_new[i]
                h=h^f1( hex(int(R[0],2))[2:] , R[1])^f1( hex(int(R[N-1],2))[2:] , R[0])
        if(j==N-1):
                h=h^f1( hex(int(R[N-2],2))[2:] , R[N-1])^f1( hex(int(R[N-1],2))[2:] , R[0])
                R[j]=R_new[i]
                h=h^f1( hex(int(R[N-2],2))[2:] , R[N-1])^f1( hex(int(R[N-1],2))[2:] , R[0])                
    
    tag_updated = DES.encrypt_DES(key_tag,hex(h))
    return tag_updated, hex(h)


In [3]:
print('hi')
key = '0e329232ea6d0d73'
D1 = ip.image_to_blocks('pic1.png')
print('hi')
tag, h = em.encrypt_message(key, D1) 
print('hi')
D2 = ip.image_to_blocks('pic2.png')
print('hi')
tag2, h2= em.encrypt_message(key, D2)
print('hi')


hi
hi
hi
hi
hi
[0, 14456] ['1111111111111111111111111111111100000000000000001111111100000000', '0000000000000000111111111111111111111111111111110000000000000000']


NameError: name 'D' is not defined

In [5]:
print(tag,h,tag2,h2)
indices , update_list = ip.difference_between_2_arrays(D1,D2)
print(indices,update_list)
tag_updated, h1 = em.incremental_update_genrate_hash(key,tag,indices,D1,update_list)   
print("\nTag_updated : ",tag_updated,"\n h1 : ",h1,"\n")
print('hi')

cddb30ef2fef1aff 0x0 e9c5d65fa36711c1 0xcbf64df780caf46e
[0, 14456] ['1111111111111111111111111111111100000000000000001111111100000000', '0000000000000000111111111111111111111111111111110000000000000000']
From em module line 56 h we have decrypted 0000000000000000

Tag_updated :  e9c5d65fa36711c1 
 h1 :  0xcbf64df780caf46e 

hi
