In [27]:
from Crypto.Hash import MD5
hash = MD5.new()
message=b"Hello Vedika"
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
4fb6563dd4ad9e2bc16f28491b12729b


In [31]:
from Crypto.Hash import MD5
hash = MD5.new()
hash.update(b'Hello ')
hash.update(b'Vedika')
print(hash.hexdigest())

4fb6563dd4ad9e2bc16f28491b12729b


In [40]:
def HEval(list_g,list_message):
    h=1
    for i in range(len(list_g)):
        print(list_g[i], list_message[i])
        h=h*(list_g[i]**(int(list_message[i],2)+1))
    return h


In [41]:
g=[2,3]
m=[b'101',b'111']
HEval(g,m)

419904

In [7]:
import Crypto.Util.number
import Crypto
import sys
import random
p=Crypto.Util.number.getPrime(5, randfunc=None) #Crypto.Random.get_random_bytes
print ("\nRandom n-bit Prime (p): ",p)


Random n-bit Prime (p):  29


In [75]:
import
random.sarandom.sa

[20, 13, 93, 19, 75, 77, 38]

In [41]:
import Crypto.Util.number
import Crypto
import random
import sys

n=5

def getPrime(k):
    #should return k+1 bit prime
    p=Crypto.Util.number.getPrime(k+1, randfunc=None) #randfunc=Crypto.Random.get_random_bytes
    return p

def SelectG(p,n):
    #should select randomly g1,..,gn from 0,..,p and return that
    g=random.sample(range(2,p),n)
    return g

def HGen(k):
    #should return hash family p,g1,..,gn
    p=getPrime(k)
    g=SelectG(p,n)
    print(p," ",g," ")
    return p,g

def HEval(p,list_g,list_message):
    h=1
    for i in range(len(list_g)):
        h=h*(list_g[i]**(int(list_message[i],2)+1))
    return h

def IncH(p,g,M,h,j,m):
    print(M[j])
    print(int(M[j],2))
    x=int(h/(g[j]**(int(M[j],2)+1)))
    y=x*(g[j]**(int(m,2)+1))
    return y

def main():
    M=[b'101',b'101',b'101',b'101',b'101']
    p,g = HGen(20)
    h=HEval(p,g,M)
    h1=IncH(p,g,M,h,2,b'111')
    M1=[b'101',b'101',b'111',b'101',b'101']
    h2=HEval(p,g,M1)
    print(h," ")
    print(h1)
    print(h2)


In [42]:
import time
start = time.process_time()
main()    
print(time.process_time() - start)

2063483   [1126102, 379344, 1565237, 1650518, 83157]  
b'101'
5
597393917380790466841018476725060416042638280714589749141359769853232198598842218764803131729591948552854508432428713875022943909651497476864060887249146120829860181186707456  
1463595303633837710415072772085709272659545010378411301503583181917415949965421757098237420228358934633057397294059238096124294280735518845152674978334741760926075335239788705164243763200
1463595303633837720686520546566322333719173841285157557620349053930694370676691303498895454721785274917171234683600360825881130213301543946330653833556996172770695561740436197455706456064
0.00992202200000003


In [6]:
fo = open("test1.jpeg","rb")
image = fo.read()
fo.close()
image = bytearray(image)
key = 48
for index, value in enumerate(image):
    image[index]=value^key
fo = open("enc.jpeg","wb")
fo.write(image)
fo.close()

In [9]:
fo = open("enc.jpeg","rb")
image = fo.read()
fo.close()
image = bytearray(image)
key = 48
for index, value in enumerate(image):
    image[index]=value^key
fo = open("denc.jpeg","wb")
fo.write(image)
fo.close()

FileNotFoundError: [Errno 2] No such file or directory: 'enc.jpeg'

In [20]:
import sys

In [51]:
fo = open("pic1.png","rb")
image1 = fo.read()
print(type(image1))
fo.close()
image1 = bytearray(image1)
print(image1[500])
#print(sys.getsizeof(image1[256]))
#print(len(image1))
fo = open("pic1-up.png","wb")
fo.write(image1)
fo.close()

<class 'bytes'>
59


In [45]:
fo2 = open("pic2.png","rb")
image2 = fo2.read()
fo2.close()
image2 = bytearray(image2)
print(image2[500])
print(sys.getsizeof(image2[256]))
print(len(image2))

59
28
114997


In [58]:
from PIL import Image

im = Image.new(mode = "RGB", size = (200, 200), color = (153, 153, 255) )
pixels = im.load()
pixels[10,10] = (0,0,0)
im.show()

In [95]:
from PIL import Image

# PIL accesses images in Cartesian co-ordinates, so it is Image[columns, rows]
img = Image.new( 'RGB', (20,20), "green") # create a new black image
pixels = img.load() # create the pixel map
print(pixels)
img.show()
img.save('pic1.jpg')
for i in range(img.size[0]):    # for every col:
        pixels[i,i] = (255, 255, 255) # set the colour accordingly
        #pixels[i,19-i] = (255, 255, 255)
img.show()
img.save('pic2.jpg')

In [97]:
fo1 = open("pic1.jpg","rb")
im1 = fo1.read()
fo1.close()
im1 = bytearray(im1)
#print(len(im1))
fo2 = open("pic2.jpg","rb")
im2 = fo2.read()
fo2.close()
im2 = bytearray(im2)
#print(len(im2))
#print(im2)
#im1

In [98]:
from PIL import Image, ImageChops

pixelsDifference = ImageChops.difference(Image.open('pic1.jpg'), Image.open('pic2.jpg')).convert('L')
pixelsDifference = pixelsDifference.point(([0] + ([255] * 255)))
Img = pixelsDifference.convert('RGB')
print(Img)

<PIL.Image.Image image mode=RGB size=20x20 at 0x7F2AFDF149E8>


In [100]:
import matplotlib.pyplot as plt 
import matplotlib.image as img 
  
# reading the image 
testImage = img.imread('pic1.jpg') 
  
# displaying the image as an array 
print(len(testImage))
#print(testImage)

# reading the image 
testImage2 = img.imread('pic2.jpg') 
  
# displaying the image as an array 
print(len(testImage2))
#print(testImage2)


20
20


In [5]:
import numpy as np
from PIL import Image

a=np.array(Image.open('pic1.jpg').convert('L'))
print(a)
a[0][0] = 255
print(a)
b=np.array(Image.open('pic2.jpg').convert('L'))
print(b)
img = Image.fromarray(b, 'RGB')
img.save('test.jpg')
img.show()

[[75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75]
 [75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75

ValueError: not enough image data

In [114]:
import numpy as np
a=np.array(Image.open('pic1.jpg').convert('L'))
key = 48

b=enumerate(a)
print(b)

In [9]:
import skimage.io

# read image
image = skimage.io.imread(fname="pic1.jpg")

In [8]:
import base64
 
with open("pic1.jpg", "rb") as imageFile:
    str = base64.b64encode(imageFile.read())
    print(str)
    print(len(str))
with open("pic2.jpg", "rb") as imageFile:
    str = base64.b64encode(imageFile.read())
    print(str)
    print(len(str))


b'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAUABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDiqKKK+aPjwooooAKKKKACiiigD//Z'
860
b'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQ

In [10]:
import skimage.io
from Crypto.Hash import MD5
import hashlib 
  

# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
#print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#Now B has 80 blocks with 15 bytes size each
#We encode blocks in counter mode using IV = 19891, cnt = 49 starting
list_blocks_int = []
blocks_cipher_list = []
counter = 49
IV = 19891
final_hash = 0
for i in range(len(B)):
    x= (int(B[i], base=2))
    c= x^counter^IV
    counter+=1
    final_hash^=c
    list_blocks_int.append(x)
    blocks_cipher_list.append(c)
print(final_hash)
print(type(final_hash))
hash = MD5.new()
message=bin(final_hash)
hash.update(message)
print(hash.hexdigest())

decrypted_blocks_list=[]

counter=49
for i in range(len(B)):
    x= blocks_cipher_list[0]
    c= x^counter^IV
    counter+=1
    decrypted_blocks_list.append(c)
print(decrypted_blocks_list)


[[[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 ...

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]

 [[  0 128   1]
  [  0 128   1]
  [  0 128   1]
  ...
  [  0 128   1]
  [  0 128   1]
  [  0 128   1]]]


In [51]:

import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#Now B has 80 blocks with 15 bytes size each
#We encode blocks in counter mode using IV = 19891, cnt = 49 starting
list_blocks_int = []
blocks_cipher_list = []
counter = 49
IV = 19891
final_hash_int = 0
for i in range(len(B)):
    x= (int(B[i], base=2))
    #print(x)
    c= x^counter^IV
    counter+=1
    final_hash_int^=c
    list_blocks_int.append(x)
    blocks_cipher_list.append(str(c))
print(final_hash_int)
temp=[]
for i in range(len(blocks_cipher_list)):
    temp.append(bin(int(blocks_cipher_list[i]))[2:].zfill(8))

final_hash_str = ''.join(temp)
print((final_hash_str))
hash = MD5.new()
message=str(final_hash_int).encode('utf-8')
#print(message)
hash.update(message)
print(hash.hexdigest())
final_hash = hash.hexdigest()

decrypted_blocks_list=[]

counter=49
#for i in range(len(B)):
#    x= blocks_cipher_list[i]
#    c= x^counter^IV
#    counter+=1
#    decrypted_blocks_list.append(c)
#print(decrypted_blocks_list)



1200
176
1100110110000011110011011000000011001101100000011100110110000110110011011000011111001101100001001100110110000101110011011000101011001101100010111100110110001000110011011000100111001101100011101100110110001111110011011000110011001101100011011100110111110010110011011111001111001101111100001100110111110001110011011111011011001101111101111100110111110100110011011111010111001101111110101100110111111011110011011111100011001101111110011100110111111110110011011111111111001101111111001100110111111101110011011110001011001101111000111100110111100000110011011110000111001101111001101100110111100111110011011110010011001101111001011100110111101010110011011110101111001101111010001100110111101001110011011110111011001101111011111100110111101100110011011110110111001101110100101100110111010011110011011101000011001101110100011100110111010110110011011101011111001101110101001100110111010101110011011101101011001101110110111100110111011000110011011101100111001101110111101100110111011111110011011101110

In [21]:
import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
# to make blocks in message M, each block is of 5 pixels, 15 bytes
print(b)
print(len(b))
B=[]
for i in range(80):
    temp = b[3*i:3*(i+1)]
    B.append(''.join(temp)) 
#print(B)
#print(len(B))

1200
['00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000', '00000001', '00000000', '10000000'

In [17]:
## CODE FOR ARRAY TO IMAGE

from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
print(data)
data[0:256, 0:256] = [255, 0, 0] # red patch in upper left
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [30]:
import skimage.io
from Crypto.Hash import MD5
# read image
a = skimage.io.imread(fname="pic1.jpg")
a=a.flatten(order='C') #flattened pixel array
print(len(a))
b=[]
# to convert pixels to binary
# message M is the join of all elements in a
for i in range(1200):
    b.append(bin(int(a[i]))[2:].zfill(8))
#print(b)
D=[]
t=''
for i in range(len(b)):
    if(i%8==0):
        t = b[i]
    
    else:
        t+=b[i]
        if((i+1)%8==0):
            D.append(t)
        elif(i==len(b)-1):
            D.append(t)
# D CONSISTS OF 150 BLOCKS OF MESSAGES, LENGTH 64 BITS EACH

1200


In [33]:
from Crypto.Hash import MD5
R =[]
#for i in D:
hash = MD5.new()
message=D[0].encode('utf-8')
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
a25a3530e4b08bf36e4eba4a62d55ce9


In [39]:
import hashlib

a = hashlib.md5(D[0].encode('utf-8'))
b = a.hexdigest()
as_int = int(b, 16)
print(as_int)
print(len(bin(as_int)[2:]))


215803320875861314203172436546581519593
128


In [55]:
def randomizer(D_is_array_64bits_blocks):
    R=[]
    for i in D_is_array_64bits_blocks:
        a = hashlib.md5(i.encode('utf-8'))
        b = a.hexdigest()
        as_int = int(b, 16)
        
        as_bin = bin(as_int)[2:66]   # taking a 64bit no. to randomize
        randomizer_number = int(as_bin, 2)
        print(as_int,as_bin,randomizer_number)
        R.append(bin(randomizer_number*int(i,2)%9223372036854775808)[2:].zfill(64))   # 2 to the power 63
    return R
print(int('0011101110111000000110111101110101100100110111011101110111000010',2))
R= randomizer(['0011101110111000000110111101110101100100110111011101110111000010'])
print(R[0])

4303220081646493122
83956083415494437196646467121856018425 1111110010100101011010011111110110010000101101110001101100010100 18205073606490659604
0001111010010101001010001111111111101101011001101100100100101000


In [56]:
18205073606490659604*4303220081646493122%9223372036854775808

2203712672332433704

In [57]:
bin(2203712672332433704)

'0b1111010010101001010001111111111101101011001101100100100101000'

In [58]:
print('1111010010101001010001111111111101101011001101100100100101000'=='1111010010101001010001111111111101101011001101100100100101000')

True
