In [27]:
from Crypto.Hash import MD5
hash = MD5.new()
message=b"Hello Vedika"
print(type(message))
hash.update(message)
print(hash.hexdigest())

<class 'bytes'>
4fb6563dd4ad9e2bc16f28491b12729b


In [11]:
from PIL import Image
import numpy as np


pic1_arr = Image.open("pic1.jpg")
pic2_arr = Image.open("pic2.jpg")

pic1_arr = np.array(pic1_arr.getdata())
pic2_arr = np.array(pic2_arr.getdata())

update_indices =[]

for i in range(400):
    if(pic1_arr[i]!=pic2_arr[i]):
        update_indices.append(i)
        


[[  0 128   1]
 [  0 128   1]
 [  0 128   1]
 ...
 [  0 128   1]
 [  0 128   1]
 [  0 128   1]] [[255 255 204]
 [ 33 112  29]
 [  0 139  21]
 ...
 [ 28 125  28]
 [ 28 118  30]
 [178 255 181]]


In [4]:
if((1==0)&1):
    print("hi")